[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[workspace]

members = [
    "camel-case",
    "to_upper",
]

[profile.release]
debug = false
lto = true
opt-level = 'z'
panic = 'abort'
codegen-units = 1
