[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[workspace]

members = [
    "function/math/constants/*",
    "function/array/append",
    "function/string/to_upper",
    "aggregate/sum",
]

[profile.release]
debug = false
lto = true
opt-level = 'z'
panic = 'abort'
codegen-units = 1
